/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as VendorTransactionsRouteImport } from './routes/vendor.transactions'
import { Route as VendorLoginRouteImport } from './routes/vendor.login'
import { Route as VendorEarningsRouteImport } from './routes/vendor.earnings'
import { Route as VendorDashboardRouteImport } from './routes/vendor.dashboard'
import { Route as RiderTransactionsRouteImport } from './routes/rider.transactions'
import { Route as RiderLoginRouteImport } from './routes/rider.login'
import { Route as RiderDashboardRouteImport } from './routes/rider.dashboard'
import { Route as HomeOrderConfirmedRouteImport } from './routes/home.order-confirmed'
import { Route as HomeCheckoutRouteImport } from './routes/home.checkout'
import { Route as HomeCartRouteImport } from './routes/home.cart'
import { Route as HomeVendorIdRouteImport } from './routes/home.vendor.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorTransactionsRoute = VendorTransactionsRouteImport.update({
  id: '/vendor/transactions',
  path: '/vendor/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorLoginRoute = VendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorEarningsRoute = VendorEarningsRouteImport.update({
  id: '/vendor/earnings',
  path: '/vendor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorDashboardRoute = VendorDashboardRouteImport.update({
  id: '/vendor/dashboard',
  path: '/vendor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderTransactionsRoute = RiderTransactionsRouteImport.update({
  id: '/rider/transactions',
  path: '/rider/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderLoginRoute = RiderLoginRouteImport.update({
  id: '/rider/login',
  path: '/rider/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderDashboardRoute = RiderDashboardRouteImport.update({
  id: '/rider/dashboard',
  path: '/rider/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeOrderConfirmedRoute = HomeOrderConfirmedRouteImport.update({
  id: '/home/order-confirmed',
  path: '/home/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCheckoutRoute = HomeCheckoutRouteImport.update({
  id: '/home/checkout',
  path: '/home/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCartRoute = HomeCartRouteImport.update({
  id: '/home/cart',
  path: '/home/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeVendorIdRoute = HomeVendorIdRouteImport.update({
  id: '/home/vendor/$id',
  path: '/home/vendor/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home/cart': typeof HomeCartRoute
  '/home/checkout': typeof HomeCheckoutRoute
  '/home/order-confirmed': typeof HomeOrderConfirmedRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/transactions': typeof RiderTransactionsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/transactions': typeof VendorTransactionsRoute
  '/home/': typeof HomeIndexRoute
  '/home/vendor/$id': typeof HomeVendorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/cart': typeof HomeCartRoute
  '/home/checkout': typeof HomeCheckoutRoute
  '/home/order-confirmed': typeof HomeOrderConfirmedRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/transactions': typeof RiderTransactionsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/transactions': typeof VendorTransactionsRoute
  '/home': typeof HomeIndexRoute
  '/home/vendor/$id': typeof HomeVendorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home/cart': typeof HomeCartRoute
  '/home/checkout': typeof HomeCheckoutRoute
  '/home/order-confirmed': typeof HomeOrderConfirmedRoute
  '/rider/dashboard': typeof RiderDashboardRoute
  '/rider/login': typeof RiderLoginRoute
  '/rider/transactions': typeof RiderTransactionsRoute
  '/vendor/dashboard': typeof VendorDashboardRoute
  '/vendor/earnings': typeof VendorEarningsRoute
  '/vendor/login': typeof VendorLoginRoute
  '/vendor/transactions': typeof VendorTransactionsRoute
  '/home/': typeof HomeIndexRoute
  '/home/vendor/$id': typeof HomeVendorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home/cart'
    | '/home/checkout'
    | '/home/order-confirmed'
    | '/rider/dashboard'
    | '/rider/login'
    | '/rider/transactions'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/login'
    | '/vendor/transactions'
    | '/home/'
    | '/home/vendor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/cart'
    | '/home/checkout'
    | '/home/order-confirmed'
    | '/rider/dashboard'
    | '/rider/login'
    | '/rider/transactions'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/login'
    | '/vendor/transactions'
    | '/home'
    | '/home/vendor/$id'
  id:
    | '__root__'
    | '/'
    | '/home/cart'
    | '/home/checkout'
    | '/home/order-confirmed'
    | '/rider/dashboard'
    | '/rider/login'
    | '/rider/transactions'
    | '/vendor/dashboard'
    | '/vendor/earnings'
    | '/vendor/login'
    | '/vendor/transactions'
    | '/home/'
    | '/home/vendor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeCartRoute: typeof HomeCartRoute
  HomeCheckoutRoute: typeof HomeCheckoutRoute
  HomeOrderConfirmedRoute: typeof HomeOrderConfirmedRoute
  RiderDashboardRoute: typeof RiderDashboardRoute
  RiderLoginRoute: typeof RiderLoginRoute
  RiderTransactionsRoute: typeof RiderTransactionsRoute
  VendorDashboardRoute: typeof VendorDashboardRoute
  VendorEarningsRoute: typeof VendorEarningsRoute
  VendorLoginRoute: typeof VendorLoginRoute
  VendorTransactionsRoute: typeof VendorTransactionsRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HomeVendorIdRoute: typeof HomeVendorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/transactions': {
      id: '/vendor/transactions'
      path: '/vendor/transactions'
      fullPath: '/vendor/transactions'
      preLoaderRoute: typeof VendorTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/login': {
      id: '/vendor/login'
      path: '/vendor/login'
      fullPath: '/vendor/login'
      preLoaderRoute: typeof VendorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/earnings': {
      id: '/vendor/earnings'
      path: '/vendor/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof VendorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/dashboard': {
      id: '/vendor/dashboard'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof VendorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/transactions': {
      id: '/rider/transactions'
      path: '/rider/transactions'
      fullPath: '/rider/transactions'
      preLoaderRoute: typeof RiderTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/login': {
      id: '/rider/login'
      path: '/rider/login'
      fullPath: '/rider/login'
      preLoaderRoute: typeof RiderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/dashboard': {
      id: '/rider/dashboard'
      path: '/rider/dashboard'
      fullPath: '/rider/dashboard'
      preLoaderRoute: typeof RiderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/order-confirmed': {
      id: '/home/order-confirmed'
      path: '/home/order-confirmed'
      fullPath: '/home/order-confirmed'
      preLoaderRoute: typeof HomeOrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/checkout': {
      id: '/home/checkout'
      path: '/home/checkout'
      fullPath: '/home/checkout'
      preLoaderRoute: typeof HomeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/cart': {
      id: '/home/cart'
      path: '/home/cart'
      fullPath: '/home/cart'
      preLoaderRoute: typeof HomeCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/vendor/$id': {
      id: '/home/vendor/$id'
      path: '/home/vendor/$id'
      fullPath: '/home/vendor/$id'
      preLoaderRoute: typeof HomeVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeCartRoute: HomeCartRoute,
  HomeCheckoutRoute: HomeCheckoutRoute,
  HomeOrderConfirmedRoute: HomeOrderConfirmedRoute,
  RiderDashboardRoute: RiderDashboardRoute,
  RiderLoginRoute: RiderLoginRoute,
  RiderTransactionsRoute: RiderTransactionsRoute,
  VendorDashboardRoute: VendorDashboardRoute,
  VendorEarningsRoute: VendorEarningsRoute,
  VendorLoginRoute: VendorLoginRoute,
  VendorTransactionsRoute: VendorTransactionsRoute,
  HomeIndexRoute: HomeIndexRoute,
  HomeVendorIdRoute: HomeVendorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
